spring.autoconfigure.exclude: org.springframework.boot.autoconfigure.web.servlet.error.ErrorMvcAutoConfiguration
cxf:
  jaxrs:
    component-scan: true
    classes-scan-packages: simplyrestful
  path: /