scannerClass: io.swagger.v3.jaxrs2.integration.JaxrsApplicationScanner
filterClass: example.nlgov_adr.AdrOpenApiFilter
openAPI:
  info:    
    version: '1.0.0'
    title: 'NLGov ADR API'
    description: 'Example API conforming to NLGov REST API Design Rules (ADR)'
    contact:
      email: arucard21@gmail.com 
  servers: 
  - url: '/v0'
    description: 'Default server'
  tags:
  - name: 'Example Resources'
    description: 'Operation for Example resources'